/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ProtectedShoppingRouteImport } from './routes/_protected.shopping'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as ProtectedRecipesRouteImport } from './routes/_protected.recipes'
import { Route as ProtectedHistoryRouteImport } from './routes/_protected.history'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedChatRouteImport } from './routes/_protected.chat'
import { Route as ProtectedBarcodeRouteImport } from './routes/_protected.barcode'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedShoppingRoute = ProtectedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRecipesRoute = ProtectedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHistoryRoute = ProtectedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatRoute = ProtectedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBarcodeRoute = ProtectedBarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/barcode': typeof ProtectedBarcodeRoute
  '/chat': typeof ProtectedChatRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/history': typeof ProtectedHistoryRoute
  '/recipes': typeof ProtectedRecipesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/shopping': typeof ProtectedShoppingRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/barcode': typeof ProtectedBarcodeRoute
  '/chat': typeof ProtectedChatRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/history': typeof ProtectedHistoryRoute
  '/recipes': typeof ProtectedRecipesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/shopping': typeof ProtectedShoppingRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/barcode': typeof ProtectedBarcodeRoute
  '/_protected/chat': typeof ProtectedChatRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/history': typeof ProtectedHistoryRoute
  '/_protected/recipes': typeof ProtectedRecipesRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/shopping': typeof ProtectedShoppingRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/barcode'
    | '/chat'
    | '/dashboard'
    | '/history'
    | '/recipes'
    | '/settings'
    | '/shopping'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/barcode'
    | '/chat'
    | '/dashboard'
    | '/history'
    | '/recipes'
    | '/settings'
    | '/shopping'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/barcode'
    | '/_protected/chat'
    | '/_protected/dashboard'
    | '/_protected/history'
    | '/_protected/recipes'
    | '/_protected/settings'
    | '/_protected/shopping'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/shopping': {
      id: '/_protected/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ProtectedShoppingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/recipes': {
      id: '/_protected/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof ProtectedRecipesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/history': {
      id: '/_protected/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof ProtectedHistoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat': {
      id: '/_protected/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedChatRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/barcode': {
      id: '/_protected/barcode'
      path: '/barcode'
      fullPath: '/barcode'
      preLoaderRoute: typeof ProtectedBarcodeRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedBarcodeRoute: typeof ProtectedBarcodeRoute
  ProtectedChatRoute: typeof ProtectedChatRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedHistoryRoute: typeof ProtectedHistoryRoute
  ProtectedRecipesRoute: typeof ProtectedRecipesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedShoppingRoute: typeof ProtectedShoppingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBarcodeRoute: ProtectedBarcodeRoute,
  ProtectedChatRoute: ProtectedChatRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedHistoryRoute: ProtectedHistoryRoute,
  ProtectedRecipesRoute: ProtectedRecipesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedShoppingRoute: ProtectedShoppingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
